### ISSUE TITLE
Question: Does it support I2c target (slave) mode?

### ISSUE THREAD

**Issue by asukiaaa** [rp-rs/i2c-pio-rs#19]
Thank you for sharing useful library.
I found examples to use this library as I2C controller (master).
https://github.com/rp-rs/rp-hal/blob/71c39a44317638fa9cb80abcd8c51219a180b7e5/boards/rp-pico/examples/pico_i2c_pio.rs
https://github.com/rp-rs/rp-hal/blob/71c39a44317638fa9cb80abcd8c51219a180b7e5/boards/rp-pico/examples/pico_i2c_oled_display_ssd1306.rs

However, I cannot find about target (slave).
Is this library support target (slave) mode?

If yes, could you add some example about it?

**Comment by ithinuel** [comment]
Hello,

First of all, to avoid any quiproquo, `pico_i2c_pio` uses the PIO peripheral to implement an I2C controller so it's not using the actual i2c block available on the rp2040.

The library does have support for [i2c peripheral-mode](https://docs.rs/rp2040-hal/latest/rp2040_hal/i2c/peripheral/struct.I2CPeripheralEventIterator.html).

It is implemented as a non-blocking event iterator. It's not the simplest code but you can have a look at https://github.com/ithinuel/wilskeeb/blob/main/firmware/src/inter_board/secondary.rs#L70 for an example.
It's basically a match that reacts to the events.

I hope that is useful. Feel free to ask questions either here or on the rp2040 [matrix channel](https://matrix.to/#/#rp-rs:matrix.org).

**Comment by asukiaaa** [comment]
Hello,

Thank you for the information.
I will try i2c peripheral (target, slave) mode.
